title: Data Avicenna
logo: /assets/img/headshot_circle.png
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
navigation:
  - name: "Home"
    link: "/"
  - name: "Other"
    link: "/other/"

git other.md _config.yml
git commit -m "Add other page and update navigation"
git push
  
